# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TARGET_URL: <change this>

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test -- -u
    - uses: actions/upload-artifact@v3
      with:
        name: webpack artifacts
        path: public/
        
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    environment: 
      name: gh-pages
      url: ${{ env.TARGET_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: webpack artifacts
          path: public
      # Deploy the docs
      - name: Deploy to docs 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh_pages
          FOLDER: public
          CLEAN: true
          SINGLE_COMMIT: true
    
